### PR TITLE
Switch CI to GitHub Actions

### PR DESCRIPTION
**Pull request by fingolfin**
Preview at https://github.com/fingolfin/PARIInterface/actions/runs/3466073653

### CODE REVIEW

**Comment by fingolfin** [comment]
@videlec are you still working on this package? interested in merging this PR? I have a few more changes I could contribute if this package is not dead after all :-). See also https://github.com/gap-packages/GaloisGroups/pull/10

**Comment by videlec** [comment]
What about the build error on `master 32`?
```
make[1]: Leaving directory '/home/runner/work/PARIInterface/PARIInterface/extern/pari'
   GAC     src/PARIInterface.c => gen/src/PARIInterface.lo
gcc -m32 -m32 -g -O2 -fPIC -MQ gen/src/PARIInterface.lo -MMD -MP -MF gen/src/PARIInterface.d -I extern/install/include -o gen/src/PARIInterface.lo -I/home/runner/gap/build -I/home/runner/gap/src -I/home/runner/gap -DUSE_GASMAN=1 -c src/PARIInterface.c
   GAC     gen/src/PARIInterface.lo => bin/x86_64-pc-linux-gnu-default32-kv8/PARIInterface.so
gcc -m32 -o bin/x86_64-pc-linux-gnu-default32-kv8/PARIInterface.so gen/src/PARIInterface.lo -m32 -shared -fPIC -R /home/runner/work/PARIInterface/PARIInterface/extern/install/lib -Lextern/install/lib -lpari
gcc: error: unrecognized command line option ‘-R’
make: *** [Makefile:95: bin/x86_64-pc-linux-gnu-default32-kv8/PARIInterface.so] Error 1
```

**Comment by fingolfin** [comment]
@videlec the build system hard coded an assumption that `gac` uses libtool, which was wrong. Fixed now.

**Comment by videlec** [comment]
thanks!

**Pull request merged**
